version: "3.8"

services:
  app:
    build: .
    container_name: edith-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://edith_user:edith_password@postgres:5432/edith_medical
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/public/uploads

  postgres:
    image: postgres:15-alpine
    container_name: edith-postgres
    environment:
      POSTGRES_DB: edith_medical
      POSTGRES_USER: edith_user
      POSTGRES_PASSWORD: edith_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edith_user -d edith_medical"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for advanced PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: edith-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@edith.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - gui

  # Optional: Adminer for simple database management
  adminer:
    image: adminer:latest
    container_name: edith-adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - gui

volumes:
  postgres_data:
  pgadmin_data:
